/* create order action type */
export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE"

/* get user orders action type */
export const GET_USER_ORDERS_REQUEST = "GET_USER_ORDERS_REQUEST"
export const GET_USER_ORDERS_SUCCESS = "GET_USER_ORDERS_SUCCESS"
export const GET_USER_ORDERS_FAILURE = "GET_USER_ORDERS_FAILURE"

/* get user notification action type */
export const GET_USER_NOTIFICATION_REQUEST = "GET_USER_NOTIFICATION_REQUEST"
export const GET_USER_NOTIFICATION_SUCCESS = "GET_USER_NOTIFICATION_SUCCESS"
export const GET_USER_NOTIFICATION_FAILURE = "GET_USER_NOTIFICATION_FAILURE"